==================================================================================================================================================
2022/03/02 起動時エラー

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\81704\AppData\Local\Programs\Python\Python39\lib\threading.py", line 973, in _bootstrap_inner    
    self.run()
  File "C:\Users\81704\AppData\Local\Programs\Python\Python39\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\81704\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\autoreload.py", line 
64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\81704\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\commands\runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\81704\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\base.py", line 469, in check
    raise SystemCheckError(msg)
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:

ERRORS:
sns.Friend.owner: (fields.E301) Field defines a relation 
with the model 'auth.User', which has been swapped out.  
        HINT: Update the relation to point at 'settings.AUTH_USER_MODEL'.
sns.Friend.user: (fields.E301) Field defines a relation with the model 'auth.User', which has been swapped out.   
        HINT: Update the relation to point at 'settings.AUTH_USER_MODEL'.
sns.Good.owner: (fields.E301) Field defines a relation with the model 'auth.User', which has been swapped out.    
        HINT: Update the relation to point at 'settings.AUTH_USER_MODEL'.
sns.Group.owner: (fields.E301) Field defines a relation with the model 'auth.User', which has been swapped out.   
        HINT: Update the relation to point at 'settings.AUTH_USER_MODEL'.
sns.Message.owner: (fields.E301) Field defines a relation with the model 'auth.User', which has been swapped out. 
        HINT: Update the relation to point at 'settings.AUTH_USER_MODEL'.

WARNINGS:
hello.Friend: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the HelloConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
hello.Message: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the HelloConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
sns.Friend: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the SnsConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
sns.Good: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the SnsConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
sns.Group: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the SnsConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
sns.Message: (models.W042) Auto-created primary key used 
when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the SnsConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.

System check identified 11 issues (0 silenced).